allowBuilds:
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@opencode/ai@2.0.12'
  - '@opencode/client@2.0.12'
  - '@opencode/plugin@2.0.12'
  - '@opencode/protocol@2.0.12'
  - '@opencode/schema@2.0.12'
  - '@opencode/util@2.0.12'
